version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongo
    volumes: 
      - ./data/db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    restart: unless-stopped
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
